### ISSUE TITLE
Не определена лицензия

### ISSUE THREAD

**Issue by sio** [hohlick/PowerBOOK#4]
У проекта на GitHub не определена лицензия, следовательно, пользователи (читатели) не могут быть уверены, что им вообще можно это читать :)

Предлагаю выбрать что-нибудь из серии [Creative Commons](https://ru.wikipedia.org/wiki/%D0%9B%D0%B8%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D0%B8_%D0%B8_%D0%B8%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B_Creative_Commons) или [Apache License 2.0](https://ru.wikipedia.org/wiki/%D0%9B%D0%B8%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F_Apache)

**Comment by hohlick** [comment]
Спасибо! Дело в том, что этот репозиторий - рабочий бэкграунд [проекта на gitbook.io](https://www.gitbook.com/book/hohlick/power-query-master-book-of-data-transfiguration).
Этот проект под CC-BY-SA 4.0 Int. В общем, прилепил сюда ту же лицензию

**Comment by sio** [comment]
Отлично!

Мне кажется, ссылку на gitbook имеет смысл разместить в описании репозитория.
